name: Crypto Function CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate Function
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate JSON Files
        run: |
          jq empty function.json && echo "✅ function.json valid"
          jq empty host.json && echo "✅ host.json valid"

      - name: Check PowerShell Syntax
        shell: pwsh
        run: |
          try {
            $null = [System.Management.Automation.PSParser]::Tokenize((Get-Content run.ps1 -Raw), [ref]$null)
            Write-Host "✅ PowerShell syntax is valid"
          }
          catch {
            Write-Error "❌ PowerShell syntax error: $_"
            exit 1
          }

  test:
    name: Test Function Logic
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4

      - name: Test External API Access
        run: |
          response=$(curl -s -w "%{http_code}" "https://api.coingecko.com/api/v3/ping")
          if [[ "${response: -3}" != "200" ]]; then
            echo "❌ Cannot reach CoinGecko API"
            exit 1
          fi
          echo "✅ External API accessible"